version : '3'

services:

 php-form:
  build: 
   context: ./php-form
  
 nginx:
  image: nginx:alpine
  volumes:
   - ../src:/var/www/monsite
   - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
  ports:
   - "80:80"
   - "443:443"

 database:
  image: mariadb:latest
  environment:
   - MYSQL_DATABASE=mybd
   - MYSQL_USER=myuser
   - MYSQL_PASSWORD=root
   - MYSQL_ROOT_PASSWORD=docker
